#!/bin/bash

while read i; do
    if [[ ! -f $i ]]; then
        wget -q https://lobsterdata.com/info/sample/$i
    fi
    unzip -n $i
done <<EOF
LOBSTER_SampleFile_AAPL_2012-06-21_10.zip
LOBSTER_SampleFile_AAPL_2012-06-21_50.zip
LOBSTER_SampleFile_AMZN_2012-06-21_10.zip
LOBSTER_SampleFile_GOOG_2012-06-21_10.zip
LOBSTER_SampleFile_INTC_2012-06-21_10.zip
LOBSTER_SampleFile_MSFT_2012-06-21_10.zip
LOBSTER_SampleFile_MSFT_2012-06-21_50.zip
LOBSTER_SampleFile_SPY_2012-06-21_50.zip
EOF
